version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Santiago"
    open-pull-requests-limit: 2
    groups:
      php-dependencies:
        patterns:
          - "*" # Groups all action updates into one PR to avoid noise
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "America/Santiago"
    open-pull-requests-limit: 2
    groups:
      actions:
        patterns:
          - "*" # Groups all action updates into one PR to avoid noise
