name: Tests

concurrency:
  group: ${{ github.ref }}
  # If there is already one running, stop the previous and start the new one.
  cancel-in-progress: true

on:
  push:
    branches:
      - "*.x"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Testing under PHP 8.5 and PHPUnit
    uses: Laragear/.github/.github/workflows/test-php-8.5-phpunit.yml@main
    secrets: inherit                    # required to pass org-wide secrets.
